config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "appointments#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  validates :name, :month, :day, :service, presence: true
  validates :day, numericality: { only_integer: true, greater_than: 0, less_than: 31 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: %i[show edit update destroy]

  # GET /appointments or /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1 or /appointments/1.json
  def show; end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit; end

  # POST /appointments or /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to appointment_url(@appointment), notice: 'Appointment was successfully created.' }
        format.turbo_stream
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1 or /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to appointment_url(@appointment), notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1 or /appointments/1.json
  def destroy
    @appointment.destroy

    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.turbo_stream
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_appointment
    @appointment = Appointment.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def appointment_params
    params.require(:appointment).permit(:name, :month, :day, :service)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_appointment.html.erb
<%= turbo_frame_tag dom_id(appointment) do %>
  <div id="<%= dom_id appointment %>">
    <div class="md:container md:mx-auto">

      <div class="p-4 my-2 bg-slate-900 rounded-xl flex flex-row space-x-4">
        <div class="text-white">Thank you <strong><%= appointment.name %></strong>, your appointment for 
          <strong><%= appointment.service %></strong>
          has been set for <strong><%= appointment.month %></strong> <strong><%= appointment.day %>
          </strong>. We look forward to seeing you then.
        </div>
        
        <div class="text-blue-700 bg-blue-200 px-1 w-fit align-middle rounded-md">
          <%= link_to "Edit", edit_appointment_path(appointment) %>
        </div>
  
        <div class="text-red-700 bg-red-200 px-1 w-fit align-middle rounded-md">
          <%= button_to "Destroy", @appointment, method: :delete %>
        </div>
      </div>
  </div>
</div>
<% end %>

app/views/appointments/_form.html.erb
<%= form_with(model: appointment) do |form| %>
  <% if appointment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
        <% appointment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex flex-row my-2">
    <%= form.label :name, class:"px-5 w-24", style: "display: block" %>
    <%= form.text_field :name, class:"px-5 border-2" %>
  </div>

  <div class="flex flex-row my-2">
    <%= form.label :month, class:"px-5 w-24", style: "display: block" %>
    <%= form.select :month, options_for_select(["", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]), class:"px-5 border-2" %>
  </div>

  <div class="flex flex-row my-2">
    <%= form.label :day, class:"px-5 w-24", style: "display: block" %>
    <%= form.select :day, options_for_select((1..31).to_a), class:"px-5 border-2" %>
  </div>

  <div class="flex flex-row my-2">
    <%= form.label :service, class:"px-5 w-24", style: "display: block" %>
    <%= form.select :service, options_for_select(["", "Car wash", "Change tires", "Review oil level", "Change motor oil", "Review emissions", "Fine tune motor", "Fix car body", "Scheduled maintenance", "Polish car body", "Fix computer", "Add refrigerator", "Clean seats"]), class:"px-5 border-2" %>
  </div>

  <div class="text-blue-700 bg-blue-200 w-fit my-4 hover:pointer px-1 w-fit align-middle rounded-md">
    <%= form.submit %>
  </div>
<% end %>

app/views/appointments/create.turbo_stream.erb
<%= turbo_stream.prepend "appointments", partial: "appointments/appointment", locals: { appointment: @appointment } %>
<%= turbo_stream.update Appointment.new, "" %>

app/views/appointments/destroy.turbo_stream.erb
<%= turbo_stream.remove @appointment %>

app/views/appointments/edit.html.erb
<h1>Editing appointment</h1>

<%= turbo_frame_tag dom_id(@appointment) do %>
  <%= render "form", appointment: @appointment %>
<% end %>

<br>

<div>
  <%= link_to "Show this appointment", @appointment %> |
  <%= link_to "Back to appointments", appointments_path %>
</div>

app/views/appointments/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="md:container md:mx-auto p-4 my-2">
<p class="text-3xl py-4"><strong>Welcome to the Car Service Appointments Maker</strong></p>

  <%= link_to "Click to make a new appointment",
    new_appointment_path,
    class: "text-blue-700 bg-blue-200 w-fit p-1 rounded-md my-5",
    data: { turbo_frame: dom_id(Appointment.new) } 
  %>

  <%= turbo_frame_tag Appointment.new %>

<div id="appointments">
  <%= turbo_frame_tag "appointments" do %>
  <% @appointments.each do |appointment| %>
    <%= render appointment %>
  <% end %>
   
  <% end %>
</div>


</div>

app/views/appointments/new.html.erb
<h1>New appointment</h1>

<%= turbo_frame_tag Appointment.new do %>
  <%= render "form", appointment: @appointment %>
<% end %>

<br>

<div>
  <%= link_to "Back to appointments", appointments_path %>
</div>

app/views/appointments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @appointment %>

<div>
  <%= link_to "Edit this appointment", edit_appointment_path(@appointment) %> |
  <%= link_to "Back to appointments", appointments_path %>

  <%= button_to "Destroy this appointment", @appointment, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookingApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.tailwindcss.com"></script>
  </head>

  <body>
    <div>
      <img src="https://i.ibb.co/4Fr26YK/pic6.jpg"
       alt="pic6" 
       style="opacity: 0.4; margin-top: -10px; width: 100%; height: 105%; position: absolute; z-index: -1;">
    </div>
    <%= yield %>

    <footer class="bg-gray-800 text-white text-center text-xs p-3 absolute bottom-0 w-full">
      &copy; 2023 BookingApp - All rights reserved - Developed by: Dario Alessio
    </footer>
  </body>
</html>